### ISSUE TITLE
IE11 support for grid-area - How to autoprefix that?

### ISSUE THREAD

**Issue by ArturJo** [ErdmannFreunde/euf_nutshell_kit#14]
Could you please help. How to get all the autoprefix for ms like grid-area and grid-gap (example: -ms-grid-column: 1;  -ms-grid-column-span: 2;  -ms-grid-row: 1;) How to activate it in my gulpfile ?

**Comment by denniserdmann** [comment]
You can configure autoprefixer to use specific versions of a browser. However it looks like the support for IE 11 ist already added, when i check the default configuration here: https://browserl.ist/?q=last+1+version.

I found some tickets at stackoverflow saying that the grid-layout support of IE11 ist really bad. So i would check first, if your problem is a bug in grid layout or a bug in autoprefixer.

As we don't give support for autoprefixer, i will close this issue here.
